# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calificacion_proyecto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.BooleanField()),
                ('descripcion_problema', models.BooleanField()),
                ('hipotesis', models.BooleanField()),
                ('objetivos_generales', models.BooleanField()),
                ('objetivos_especificos', models.BooleanField()),
                ('justificacion', models.BooleanField()),
                ('marco_de_referencia_teorico_conceptual', models.BooleanField()),
                ('metodologia', models.BooleanField()),
                ('resultados_esperados', models.BooleanField()),
                ('cronograma_de_actividades', models.BooleanField()),
                ('recursos_o_presupuesto', models.BooleanField()),
                ('literatura_citada', models.BooleanField()),
                ('redaccion_y_ortografia', models.BooleanField()),
                ('pertenece_al_area_formacion_estudiante', models.BooleanField()),
                ('recomendaciones_observaciones_correciones', models.TextField()),
                ('resultado_consolidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacionproyecto_resultado_consolidado', to='evaluacion.CalificacionProyecto')),
                ('trabajo_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TrabajoGrado')),
            ],
        ),
    ]
