# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionDeGrado',
            fields=[
                ('id_opcion_grado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_opcion_de_grado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo_de_grado', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
