# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionDeGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion_de_grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo_de_grado', models.CharField(max_length=50)),
                ('codirector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_codirector', to='universidad.Docente')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_director', to='universidad.Docente')),
                ('estudiante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_estudiante1', to='universidad.Estudiante')),
                ('estudiante2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_estudiante2r', to='universidad.Estudiante')),
                ('jurado1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_jurado1', to=settings.AUTH_USER_MODEL)),
                ('jurado2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_jurado2', to=settings.AUTH_USER_MODEL)),
                ('opcion_de_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.OpcionDeGrado')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Programa')),
            ],
        ),
    ]
