# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universidad', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajogrado',
            name='codirector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_codirector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='estudiante1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_estudiante1', to='universidad.Estudiante'),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='estudiante2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_estudiante2', to='universidad.Estudiante'),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='jurado1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_jurado1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='jurado2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajogrado_jurado2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='opcion_de_grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.OpcionDeGrado'),
        ),
        migrations.AddField(
            model_name='trabajogrado',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Programa'),
        ),
    ]
